spring:
  profiles:
    active:
      - 7001
---
server:
  port: 7001
spring:
  profiles: 7001
  application:
    name: spring-cloud-eureka
eureka:
  instance:
    hostname: eureka7001.com
    instanc e-id: eureka-7001
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
server:
  port: 7002
spring:
  profiles: 7002
  application:
    name: spring-cloud-eureka
eureka:
  instance:
    hostname: eureka7001.com
    instanc e-id: eureka-7001
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
server:
  port: 7003
spring:
  profiles: 7003
  application:
    name: spring-cloud-eureka
eureka:
  instance:
    hostname: eureka7001.com
    instanc e-id: eureka-7001
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ 